[build]
  publish = "client" # Directory where static files are located
  command = "" # Leave empty if no build command is needed

[functions]
  directory = "netlify/functions" # Directory where Netlify functions are located
